files:
  description: 'Load files'
  name: 'Local file loader'
  path: data_loaders/files.py
  type: data_loader
  inputs:
    text:
      style:
        monospace: true
      type: text_field
  variables:
    path:
      description: 'Path to file directory'
      name: 'Directory path'
      input: text
      required: true
      types:
        - string
    exclude_pattern:
      name: 'Exclude pattern'
      description: 'Exclude pattern'
      input: text
      required: false
      types:
        - string
    include_pattern:
      name: 'Include pattern'
      description: 'Include pattern'
      input: text
      required: false
      types:
        - string
github:
  description: 'Fetch GitHub repository'
  name: 'GitHub repository loader'
  type: data_loader
  inputs:
    text:
      style:
        monospace: true
      type: text_field
  variables:
    url:
      description: 'GitHub repository URL'
      name: 'Repo URL'
      input: text
      required: true
      types:
        - string
